version: "2"

services:
  backend:
    container_name: backend
    image: schmidtp0740/moei_backend:master-c86a00f28ed9f456f6e437e8095950a690bd6548
    command: nodemon -L
    ports:
      - "8080:8080"
  portals:
    container_name: portals
    build: .
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - "./portals/:/portals/"
      - "/portals/node_modules"
